<?php
return [
    'welcome' => 'Welcome to',
    'hotel' => 'HOTEL',
    'about_us' => 'About Us',
    'accommodation' => 'Accommodation',
    'menu' => 'Menu',
    'tour_travel' => 'Tour travel',
    'service' => 'Service',
    'news' => 'News',
    'gallery' => 'Gallery',
    'contact' => 'Contact',
    'book_room' => 'Book a room',
    'login' => 'Login',
    'logout' => 'Logout',
    'hello' => 'Hello, ',
    'read_more' => 'Read more',
    'double_room' => 'Double Room',
    'triple_room' => 'Triple Room',
    'dorm_room' => 'Dorm Room',
    'travel_1' => 'Bich Dong Pahoga Mua Cave - Phat Diem Cathedral',
    'travel_2' => 'Travel Destination 2',
    'travel_3' => 'Travel Destination 3',
    'travel_4' => 'Travel Destination 4',
    'travel_5' => 'Travel Destination 5',
    'travel_6' => 'Travel Destination 6',
];?>